server:
  port: 8090

spring:
  application:
    name: news
  datasource:
    platform: h2
    url: jdbc:h2:file:~/data/productDB
    driver-class-name: org.h2.Driver
    username: sa
    password: sa
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true