server:
  port: 8098

spring:
  cache:
    type: redis
  application:
    name: web-api
  datasource:
    platform: h2
    url: jdbc:h2:mem:mydb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  redis:
    host: ${REDIS_URL}
    port: ${REDIS_PORT}
    timeout: 1000
  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss.SSS"
    time-zone: "GMT+3"
    serialization:
      fail_on_empty_beans: false

elasticsearch:
  host: ${ES_URL}
  port: ${ES_PORT}

cache:
  expirations:
    category: 7200